export const expencesList = [
    {
      id: "e1",
      title: "Tomatoes",
      amount: 94.12,
      date: new Date(2020, 7, 14),
      category: 'food',
    },
    {
      id: "e2",
      title: "New smart-TV",
      amount: 799.49,
      date: new Date(2021, 2, 12),
      category: 'home',
    },
    {
      id: "e3",
      title: "Car Insurance",
      amount: 294.67,
      date: new Date(2021, 2, 28),
      category: 'car',
    },
    {
      id: "e4",
      title: "New Desk (Wooden)",
      amount: 450,
      date: new Date(2021, 5, 12),
      category: 'party',
    },
    {
      id: "e5",
      title: "New Desk (Plastik)",
      amount: 450,
      date: new Date(2021, 5, 12),
      category: 'food',
    },
    {
      id: "e6",
      title: "A Boat",
      amount: 45230,
      date: new Date(2021, 5, 12),
      category: 'travel',
    },
    {
      id: "e7",
      title: "New Dog",
      amount: 1450,
      date: new Date(2021, 5, 12),
      category: 'clothes',
    },
  ];